/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* f_ang_a:(i0[6],i1[2])->(o0,o1,o2) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[1]!=0) res[1][0]=a0;
  a0=1.3000000000000000e-01;
  a1=9.7944511500000004e+00;
  a2=2.2799999999999998e+00;
  a3=5.;
  a4=arg[0]? arg[0][1] : 0;
  a5=arg[0]? arg[0][2] : 0;
  a6=(a0*a5);
  a6=(a4+a6);
  a7=arg[1]? arg[1][1] : 0;
  a8=cos(a7);
  a6=(a6*a8);
  a8=arg[0]? arg[0][0] : 0;
  a9=sin(a7);
  a9=(a8*a9);
  a6=(a6-a9);
  a9=cos(a7);
  a9=(a8*a9);
  a10=(a0*a5);
  a10=(a4+a10);
  a11=sin(a7);
  a10=(a10*a11);
  a9=(a9+a10);
  a6=atan2(a6,a9);
  a6=(a3*a6);
  a6=(-a6);
  a6=atan(a6);
  a6=(a2*a6);
  a6=sin(a6);
  a6=(a1*a6);
  a6=(a0*a6);
  a7=cos(a7);
  a6=(a6*a7);
  a5=(a0*a5);
  a4=(a4-a5);
  a4=atan2(a4,a8);
  a3=(a3*a4);
  a3=(-a3);
  a3=atan(a3);
  a2=(a2*a3);
  a2=sin(a2);
  a1=(a1*a2);
  a0=(a0*a1);
  a6=(a6-a0);
  a0=2.7230000000000001e-02;
  a6=(a6/a0);
  if (res[2]!=0) res[2][0]=a6;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_ang_a(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_ang_a_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_ang_a_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_ang_a_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_ang_a_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_ang_a_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_ang_a_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_ang_a_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_ang_a_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int f_ang_a_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f_ang_a_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_ang_a_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_ang_a_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_ang_a_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_ang_a_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_ang_a_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
