/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[32] = {6, 6, 0, 6, 12, 16, 19, 21, 23, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 3, 4, 5, 3, 4, 3, 4};

/* fA:(i0[6],i1[2])->(o0[6x6,23nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a4, a5, a6, a7, a8, a9;
  a0=4.5071438229593902e-01;
  a1=arg[1]? arg[1][1] : 0;
  a2=sin(a1);
  a3=9.7944511500000004e+00;
  a4=2.2799999999999998e+00;
  a5=5.;
  a6=arg[0]? arg[0][1] : 0;
  a7=1.3000000000000000e-01;
  a8=arg[0]? arg[0][2] : 0;
  a9=(a7*a8);
  a9=(a6+a9);
  a10=cos(a1);
  a9=(a9*a10);
  a11=arg[0]? arg[0][0] : 0;
  a12=sin(a1);
  a13=(a11*a12);
  a9=(a9-a13);
  a13=cos(a1);
  a14=(a11*a13);
  a15=(a7*a8);
  a15=(a6+a15);
  a16=sin(a1);
  a15=(a15*a16);
  a14=(a14+a15);
  a15=atan2(a9,a14);
  a15=(a5*a15);
  a17=(-a15);
  a17=atan(a17);
  a17=(a4*a17);
  a17=cos(a17);
  a18=casadi_sq(a9);
  a19=casadi_sq(a14);
  a18=(a18+a19);
  a14=(a14/a18);
  a12=(a14*a12);
  a9=(a9/a18);
  a13=(a9*a13);
  a12=(a12+a13);
  a12=(a5*a12);
  a13=1.;
  a15=casadi_sq(a15);
  a15=(a13+a15);
  a12=(a12/a15);
  a12=(a4*a12);
  a12=(a17*a12);
  a12=(a3*a12);
  a18=(a2*a12);
  a18=(a0*a18);
  a18=(-a18);
  if (res[0]!=0) res[0][0]=a18;
  a18=cos(a1);
  a19=(a18*a12);
  a20=(a7*a8);
  a20=(a6-a20);
  a21=atan2(a20,a11);
  a21=(a5*a21);
  a22=(-a21);
  a22=atan(a22);
  a22=(a4*a22);
  a22=cos(a22);
  a23=casadi_sq(a20);
  a24=casadi_sq(a11);
  a23=(a23+a24);
  a20=(a20/a23);
  a20=(a5*a20);
  a21=casadi_sq(a21);
  a21=(a13+a21);
  a20=(a20/a21);
  a20=(a4*a20);
  a20=(a22*a20);
  a20=(a3*a20);
  a19=(a19+a20);
  a19=(a0*a19);
  a19=(a19-a8);
  if (res[0]!=0) res[0][1]=a19;
  a19=3.6724201248622840e+01;
  a1=cos(a1);
  a12=(a7*a12);
  a12=(a1*a12);
  a20=(a7*a20);
  a12=(a12-a20);
  a12=(a19*a12);
  if (res[0]!=0) res[0][2]=a12;
  a12=8.6767895878524937e-01;
  a20=2.2509999999999999e+00;
  a24=arg[0]? arg[0][4] : 0;
  a25=1.7461412207630154e+01;
  a24=fmod(a24,a25);
  a24=(a24+a25);
  a24=fmod(a24,a25);
  a20=(a20<=a24);
  a12=(a12*a20);
  a20=-8.6767895878524937e-01;
  a25=5.8716855332622373e+00;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=-9.8023118752557803e-01;
  a25=6.7726855332622371e+00;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=9.8023118752557803e-01;
  a25=8.3751608949777694e+00;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=8.1421124303594949e-01;
  a25=8.5251608949777697e+00;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=-8.1421124303594949e-01;
  a25=1.2383610014245315e+01;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=8.1925075422272564e-01;
  a25=1.4638150014245316e+01;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=-8.1925075422272564e-01;
  a25=1.6555507207630153e+01;
  a25=(a25<=a24);
  a20=(a20*a25);
  a12=(a12+a20);
  a20=arg[0]? arg[0][3] : 0;
  a25=cos(a20);
  a24=(a12*a25);
  a26=arg[0]? arg[0][5] : 0;
  a27=(a26*a12);
  a27=(a13-a27);
  a24=(a24/a27);
  a24=(-a24);
  if (res[0]!=0) res[0][3]=a24;
  a24=cos(a20);
  a26=(a26*a12);
  a26=(a13-a26);
  a28=(a24/a26);
  if (res[0]!=0) res[0][4]=a28;
  a28=sin(a20);
  if (res[0]!=0) res[0][5]=a28;
  a28=(a14*a10);
  a29=(a9*a16);
  a28=(a28-a29);
  a28=(a5*a28);
  a28=(a28/a15);
  a28=(a4*a28);
  a28=(a17*a28);
  a28=(a3*a28);
  a29=(a2*a28);
  a29=(a0*a29);
  a29=(a29+a8);
  if (res[0]!=0) res[0][6]=a29;
  a29=(a18*a28);
  a23=(a11/a23);
  a8=(a5*a23);
  a8=(a8/a21);
  a8=(a4*a8);
  a8=(a22*a8);
  a8=(a3*a8);
  a29=(a29+a8);
  a29=(a0*a29);
  a29=(-a29);
  if (res[0]!=0) res[0][7]=a29;
  a8=(a7*a8);
  a28=(a7*a28);
  a28=(a1*a28);
  a8=(a8-a28);
  a8=(a19*a8);
  if (res[0]!=0) res[0][8]=a8;
  a8=sin(a20);
  a28=(a12*a8);
  a28=(a28/a27);
  if (res[0]!=0) res[0][9]=a28;
  a28=sin(a20);
  a29=(a28/a26);
  a29=(-a29);
  if (res[0]!=0) res[0][10]=a29;
  a29=cos(a20);
  if (res[0]!=0) res[0][11]=a29;
  a10=(a7*a10);
  a14=(a14*a10);
  a16=(a7*a16);
  a9=(a9*a16);
  a14=(a14-a9);
  a14=(a5*a14);
  a14=(a14/a15);
  a14=(a4*a14);
  a17=(a17*a14);
  a17=(a3*a17);
  a2=(a2*a17);
  a2=(a0*a2);
  a2=(a2+a6);
  if (res[0]!=0) res[0][12]=a2;
  a18=(a18*a17);
  a2=-1.3000000000000000e-01;
  a2=(a2*a23);
  a5=(a5*a2);
  a5=(a5/a21);
  a4=(a4*a5);
  a22=(a22*a4);
  a3=(a3*a22);
  a18=(a18+a3);
  a0=(a0*a18);
  a0=(a0+a11);
  a0=(-a0);
  if (res[0]!=0) res[0][13]=a0;
  a3=(a7*a3);
  a7=(a7*a17);
  a1=(a1*a7);
  a3=(a3-a1);
  a19=(a19*a3);
  if (res[0]!=0) res[0][14]=a19;
  if (res[0]!=0) res[0][15]=a13;
  a13=sin(a20);
  a13=(a11*a13);
  a19=cos(a20);
  a19=(a6*a19);
  a13=(a13+a19);
  a13=(a12*a13);
  a13=(a13/a27);
  if (res[0]!=0) res[0][16]=a13;
  a13=sin(a20);
  a13=(a11*a13);
  a19=cos(a20);
  a19=(a6*a19);
  a13=(a13+a19);
  a13=(a13/a26);
  a13=(-a13);
  if (res[0]!=0) res[0][17]=a13;
  a13=cos(a20);
  a13=(a11*a13);
  a20=sin(a20);
  a20=(a6*a20);
  a13=(a13-a20);
  if (res[0]!=0) res[0][18]=a13;
  a13=0.;
  if (res[0]!=0) res[0][19]=a13;
  if (res[0]!=0) res[0][20]=a13;
  a25=(a11*a25);
  a8=(a6*a8);
  a25=(a25-a8);
  a25=(a12*a25);
  a25=(a25/a27);
  a25=(a25/a27);
  a25=(a25*a12);
  a25=(-a25);
  if (res[0]!=0) res[0][21]=a25;
  a11=(a11*a24);
  a6=(a6*a28);
  a11=(a11-a6);
  a11=(a11/a26);
  a11=(a11/a26);
  a11=(a11*a12);
  if (res[0]!=0) res[0][22]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int fA(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fA_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fA_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fA_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fA_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fA_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fA_incref(void) {
}

CASADI_SYMBOL_EXPORT void fA_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fA_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int fA_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fA_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fA_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fA_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fA_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fA_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fA_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
