/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[10] = {6, 2, 0, 2, 5, 0, 1, 0, 1, 2};

/* fB:(i0[6],i1[2])->(o0[6x2,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000000e-01;
  a1=arg[1]? arg[1][1] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a2=(a0+a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=sin(a1);
  a0=(a0*a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a2=2.;
  a0=(a0/a2);
  a2=sin(a1);
  a2=(a0*a2);
  a3=4.5071438229593902e-01;
  a4=sin(a1);
  a5=9.7944511500000004e+00;
  a6=2.2799999999999998e+00;
  a7=5.;
  a8=arg[0]? arg[0][1] : 0;
  a9=1.3000000000000000e-01;
  a10=arg[0]? arg[0][2] : 0;
  a11=(a9*a10);
  a11=(a8+a11);
  a12=cos(a1);
  a12=(a11*a12);
  a13=arg[0]? arg[0][0] : 0;
  a14=sin(a1);
  a14=(a13*a14);
  a12=(a12-a14);
  a14=cos(a1);
  a14=(a13*a14);
  a10=(a9*a10);
  a8=(a8+a10);
  a10=sin(a1);
  a10=(a8*a10);
  a14=(a14+a10);
  a10=atan2(a12,a14);
  a10=(a7*a10);
  a15=(-a10);
  a15=atan(a15);
  a15=(a6*a15);
  a16=cos(a15);
  a17=casadi_sq(a12);
  a18=casadi_sq(a14);
  a17=(a17+a18);
  a14=(a14/a17);
  a18=sin(a1);
  a11=(a11*a18);
  a18=cos(a1);
  a18=(a13*a18);
  a11=(a11+a18);
  a14=(a14*a11);
  a12=(a12/a17);
  a17=cos(a1);
  a8=(a8*a17);
  a17=sin(a1);
  a13=(a13*a17);
  a8=(a8-a13);
  a12=(a12*a8);
  a14=(a14+a12);
  a7=(a7*a14);
  a14=1.;
  a10=casadi_sq(a10);
  a14=(a14+a10);
  a7=(a7/a14);
  a6=(a6*a7);
  a16=(a16*a6);
  a16=(a5*a16);
  a4=(a4*a16);
  a15=sin(a15);
  a5=(a5*a15);
  a15=cos(a1);
  a15=(a5*a15);
  a4=(a4+a15);
  a4=(a3*a4);
  a2=(a2+a4);
  a2=(-a2);
  if (res[0]!=0) res[0][2]=a2;
  a2=cos(a1);
  a0=(a0*a2);
  a2=cos(a1);
  a2=(a2*a16);
  a4=sin(a1);
  a4=(a5*a4);
  a2=(a2-a4);
  a3=(a3*a2);
  a0=(a0+a3);
  if (res[0]!=0) res[0][3]=a0;
  a0=3.6724201248622840e+01;
  a3=cos(a1);
  a16=(a9*a16);
  a3=(a3*a16);
  a9=(a9*a5);
  a1=sin(a1);
  a9=(a9*a1);
  a3=(a3-a9);
  a0=(a0*a3);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fB(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fB_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fB_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fB_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fB_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fB_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fB_incref(void) {
}

CASADI_SYMBOL_EXPORT void fB_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fB_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int fB_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fB_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fB_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fB_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fB_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fB_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fB_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
