/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};

/* fc:(i0[6],i1[2])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=2.;
  a2=(a0/a1);
  a0=(a0/a1);
  a1=arg[1]? arg[1][1] : 0;
  a3=cos(a1);
  a3=(a0*a3);
  a2=(a2+a3);
  a3=9.7944511500000004e+00;
  a4=2.2799999999999998e+00;
  a5=5.;
  a6=arg[0]? arg[0][1] : 0;
  a7=1.3000000000000000e-01;
  a8=arg[0]? arg[0][2] : 0;
  a9=(a7*a8);
  a9=(a6+a9);
  a10=cos(a1);
  a9=(a9*a10);
  a10=arg[0]? arg[0][0] : 0;
  a11=sin(a1);
  a11=(a10*a11);
  a9=(a9-a11);
  a11=cos(a1);
  a11=(a10*a11);
  a12=(a7*a8);
  a12=(a6+a12);
  a13=sin(a1);
  a12=(a12*a13);
  a11=(a11+a12);
  a9=atan2(a9,a11);
  a9=(a5*a9);
  a9=(-a9);
  a9=atan(a9);
  a9=(a4*a9);
  a9=sin(a9);
  a9=(a3*a9);
  a11=sin(a1);
  a11=(a9*a11);
  a12=2.2187000000000001e+00;
  a11=(a11/a12);
  a2=(a2-a11);
  a11=(a8*a6);
  a2=(a2+a11);
  if (res[0]!=0) res[0][0]=a2;
  a2=sin(a1);
  a0=(a0*a2);
  a2=cos(a1);
  a2=(a9*a2);
  a11=(a7*a8);
  a11=(a6-a11);
  a11=atan2(a11,a10);
  a5=(a5*a11);
  a5=(-a5);
  a5=atan(a5);
  a4=(a4*a5);
  a4=sin(a4);
  a3=(a3*a4);
  a2=(a2+a3);
  a2=(a2/a12);
  a0=(a0+a2);
  a2=(a8*a10);
  a0=(a0-a2);
  if (res[0]!=0) res[0][1]=a0;
  a9=(a7*a9);
  a1=cos(a1);
  a9=(a9*a1);
  a7=(a7*a3);
  a9=(a9-a7);
  a7=2.7230000000000001e-02;
  a9=(a9/a7);
  if (res[0]!=0) res[0][2]=a9;
  a9=8.6767895878524937e-01;
  a7=2.2509999999999999e+00;
  a3=arg[0]? arg[0][4] : 0;
  a1=1.7461412207630154e+01;
  a3=fmod(a3,a1);
  a3=(a3+a1);
  a3=fmod(a3,a1);
  a7=(a7<=a3);
  a9=(a9*a7);
  a7=-8.6767895878524937e-01;
  a1=5.8716855332622373e+00;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=-9.8023118752557803e-01;
  a1=6.7726855332622371e+00;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=9.8023118752557803e-01;
  a1=8.3751608949777694e+00;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=8.1421124303594949e-01;
  a1=8.5251608949777697e+00;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=-8.1421124303594949e-01;
  a1=1.2383610014245315e+01;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=8.1925075422272564e-01;
  a1=1.4638150014245316e+01;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=-8.1925075422272564e-01;
  a1=1.6555507207630153e+01;
  a1=(a1<=a3);
  a7=(a7*a1);
  a9=(a9+a7);
  a7=arg[0]? arg[0][3] : 0;
  a1=cos(a7);
  a1=(a10*a1);
  a3=sin(a7);
  a3=(a6*a3);
  a1=(a1-a3);
  a1=(a9*a1);
  a3=1.;
  a0=arg[0]? arg[0][5] : 0;
  a2=(a0*a9);
  a2=(a3-a2);
  a1=(a1/a2);
  a8=(a8-a1);
  if (res[0]!=0) res[0][3]=a8;
  a8=cos(a7);
  a8=(a10*a8);
  a1=sin(a7);
  a1=(a6*a1);
  a8=(a8-a1);
  a0=(a0*a9);
  a3=(a3-a0);
  a8=(a8/a3);
  if (res[0]!=0) res[0][4]=a8;
  a8=sin(a7);
  a10=(a10*a8);
  a7=cos(a7);
  a6=(a6*a7);
  a10=(a10+a6);
  if (res[0]!=0) res[0][5]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int fc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fc_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fc_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fc_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fc_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fc_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fc_incref(void) {
}

CASADI_SYMBOL_EXPORT void fc_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fc_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int fc_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fc_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fc_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fc_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fc_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fc_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
