model_hparams: # the hyper parameters for the most naive version of domain adversarial domain adaptation

    lr_discriminator: !!float 1e-4 # the orginal value is 1e-3
    lr_actor: !!float 1e-3 # the original value is 1.5e-6
    
    encoder_output_dim : 512
    dis_info_mode : "state_curvature"
  
    weight_decay: !!float 1e-4